name: stateless_widget
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree/static/Figtree-Black.ttf
        - asset: assets/fonts/Figtree/static/Figtree-Regular.ttf
        - asset: assets/fonts/Figtree/static/Figtree-Medium.ttf
        - asset: assets/fonts/Figtree/static/Figtree-Bold.ttf
